export { default as Home } from './Home/Home'
export { default as Login } from './Login/Login'
export { default as Register } from './Register/Register'
export { default as Sandboxing } from './Sandboxing/Sandboxing'
export { default as SandboxingHeader } from './Sandboxing/SandboxingHeader'
export { default as Course } from './Course/Course'
export { default as Contact } from './ContactUs/ContactUs'
export { default as Services } from './Services/Services'